describe("calculator", () => {
	beforeEach(() => {
		cy.visit("/")
	})
	it("correctly handle calculation", () => {
		cy.getCalculatorButton("4").click()
		cy.getCalculatorButton(".").click()
		cy.getCalculatorButton("1").click()
		cy.get(".primary-operand").should("have.text", "4.1")
		//cy.contains(".calculator-grid > button", "4").click()
		//cy.contains(".calculator-grid > button", "4").click()
		cy.contains("+").click()
		cy.contains("6").click()
		cy.contains("=").click()
		cy.get(".primary-operand").should("have.text", "10.1")
	})
	it("correctly handle AC", () => {
		cy.getCalculatorButton("4").click()
		cy.getCalculatorButton("+").click()
		cy.getCalculatorButton("6").click()
		cy.getCalculatorButton("AC").click()
		cy.get(".primary-operand").should("have.text", "0")
		cy.get(".secondary-operand").should("have.text", "")
	})
	it("correctly handle Del", () => {
		cy.getCalculatorButton("4").click()
		cy.getCalculatorButton("4").click()
		cy.getCalculatorButton("4").click()
		cy.getCalculatorButton("DEL").click()
		cy.get(".primary-operand").should("have.text", "44")
	})
})
